name: CD/CI
on:
  - push
jobs:
  Mkdocs-project:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3

      - name: "List repository files"
        run: "ls -al"
      - name: "Install python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: "Install mkdocs"
        run: pip install mkdocs
      - name: "Deploy project"
        run: mkdocs gh-deploy --force
      - name: "finish"
        run: echo "🎉 The job was successful."
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: moudjames23/spring-collab
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
